#
# Alternative firmware based on ESPHome project.
# It it more flexible as it's up to you what additional sensors you want to support.
#
# That firmware uses custom sensor that parses BLE advertisements.
#
---
esphome:
  name: meter
  platform: ESP32
  board: esp-wrover-kit
  includes:
    - elehant_ble.h

wifi:
  networks: !secret wifi_networks

  ap:
    ssid: "Meter Fallback Hotspot"
    password: !secret wifi_ap_passwd

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  # password: "test"

ota:
  # password: "test"

web_server:

esp32_ble_tracker:
  id: ble_tracker
  scan_parameters:
    interval: 100ms
    window: 99ms
    duration: 5min
    active: false

time:
  - platform: homeassistant
    id: esp_time
  - platform: sntp
    id: ntp_time
    timezone: Europe/Moscow

text_sensor:
  - platform: wifi_info
    ssid:
      name: SSID
    bssid:
      name: BSSID

  - platform: version
    name: "ESPHome version"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 10s

  - platform: esp32_hall
    name: "ESP32 Hall Sensor"
    update_interval: 10s

  - platform: uptime
    name: "Uptime"

  - platform: xiaomi_lywsdcgq
    mac_address: 4C:65:A8:D0:7F:A4
    # mac_address: 4C:65:A8:D9:9D:9D
    temperature:
      name: "Room1 Temperature"
    humidity:
      name: "Room1 Humidity"
    battery_level:
      name: "Room1 temperature/humidity sensor Battery Level"

  - platform: custom
    lambda: |-
      auto meter1 = new ElehantBLE();

      // Set serial number of the device! Like a mac_address for other BLE sensors.
      meter1->set_serial_no(9953);

      // Register
      App.register_component(meter1);
      id(ble_tracker)->register_listener(meter1);
      return {meter1->total_m3_, meter1->total_l_, meter1->rssi_};

    sensors:
      - name: Water1 Total
        unit_of_measurement: m3
        icon: mdi:water-pump
        id: water1_total_m3
      - name: Water1 Total (liters)
        unit_of_measurement: L
        icon: mdi:water-pump
        id: water1_total_l
      - name: Water1 Meter RSSI
        icon: mdi:signal
        id: water1_rssi

